name: TrackSeries.TheTVDB.HealthCheck PR Build

on: [pull_request]

jobs:
  build:
    name: Build, Test, Pack
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: .NET Build
      run: dotnet build -c Release /p:CI=true
    - name: .NET Test
      run: dotnet test -c Release --no-build /p:CI=true
    - name: .NET Lib Pack
      run: dotnet pack --no-build -c Release /p:Packing=true /p:CI=true