name: Publish to Github Packages

on:
    push:
        branches:
          - master

jobs:
  publish:
    name: Build, Test, Pack, Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: .NET Build
      run: dotnet build -c Release /p:CI=true
    - name: .NET Test
      run: dotnet test -c Release --no-build /p:CI=true
    - name: .NET Lib Pack
      run: dotnet pack --no-build -c Release /p:Packing=true /p:CI=true
    - name: Push package to Github Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path:  '**/*.nupkg'
        repo-owner:  'trackseries'
        gh-user:  ${{ github.actor }}
        token:  ${{ secrets.GITHUB_TOKEN }}


        